In [1]:
import torch
import numpy as np

In [3]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [4]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

In [6]:
x_ones = torch.ones_like(x_data)
print(f"Ons Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data,dtype = torch.float)
print(f"Rand: \n {x_rand} \n")

Ons Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Rand: 
 tensor([[0.2890, 0.6258],
        [0.8392, 0.7880]]) 



In [ ]:
shape = (2,3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
