In [1]:
import torch
import numpy as np

In [3]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [4]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

In [5]:
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.0019, 0.1483],
        [0.1809, 0.3066]]) 



In [20]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor} \n")

Random Tensor: 
 tensor([[0.5249, 0.5690, 0.6655],
        [0.6252, 0.2581, 0.6431]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



In [21]:
tensor = torch.rand(3,4)
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [23]:
if torch.accelerator.is_available():
    tensor = tensor.to(torch.accelerator.current_accelerator())
print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cuda:0


In [24]:
tensor = torch.randn(4,4)
print(f"Original tensor: \n {tensor} \n")
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:,0]}")
print(f"Last column: {tensor[:,-1]}")
tensor[:,1] = 0
print(f"Modified tensor: \n {tensor}")



Original tensor: 
 tensor([[-1.6780,  1.9692,  0.2381,  0.5001],
        [ 2.3072, -1.8802,  1.1045,  0.7310],
        [ 1.2974,  0.0948,  0.0789, -0.1695],
        [ 0.9254,  1.4240, -0.3302,  0.8286]]) 

First row: tensor([-1.6780,  1.9692,  0.2381,  0.5001])
First column: tensor([-1.6780,  2.3072,  1.2974,  0.9254])
Last column: tensor([ 0.5001,  0.7310, -0.1695,  0.8286])
Modified tensor: 
 tensor([[-1.6780,  0.0000,  0.2381,  0.5001],
        [ 2.3072,  0.0000,  1.1045,  0.7310],
        [ 1.2974,  0.0000,  0.0789, -0.1695],
        [ 0.9254,  0.0000, -0.3302,  0.8286]])


In [27]:
t1 = torch.cat([tensor, tensor,tensor], dim=0)
print(t1)
print(t1.shape)

tensor([[-1.6780,  0.0000,  0.2381,  0.5001],
        [ 2.3072,  0.0000,  1.1045,  0.7310],
        [ 1.2974,  0.0000,  0.0789, -0.1695],
        [ 0.9254,  0.0000, -0.3302,  0.8286],
        [-1.6780,  0.0000,  0.2381,  0.5001],
        [ 2.3072,  0.0000,  1.1045,  0.7310],
        [ 1.2974,  0.0000,  0.0789, -0.1695],
        [ 0.9254,  0.0000, -0.3302,  0.8286],
        [-1.6780,  0.0000,  0.2381,  0.5001],
        [ 2.3072,  0.0000,  1.1045,  0.7310],
        [ 1.2974,  0.0000,  0.0789, -0.1695],
        [ 0.9254,  0.0000, -0.3302,  0.8286]])
torch.Size([12, 4])


In [31]:
tensor = torch.rand(3,4).to(torch.accelerator.current_accelerator() if torch.accelerator.is_available() else 'cpu')
print(f"Shape of tensor: {tensor.shape}")
print(f"Tensor: {tensor}")

Shape of tensor: torch.Size([3, 4])
Tensor: tensor([[0.4128, 0.3994, 0.2346, 0.8174],
        [0.6250, 0.9206, 0.8515, 0.6128],
        [0.4895, 0.9669, 0.7671, 0.5651]], device='cuda:0')


In [37]:
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
print(f"y1: {y1} \n y2: {y2} \n y3: {y3}")
torch.matmul(tensor, tensor.T,out=y3)
print(f"y3: {y3}")

z1 = tensor * tensor
z2 = tensor.mul(tensor)
z3 = torch.rand_like(tensor)
print(f"z1: {z1} \n z2: {z2} \n z3: {z3}")
torch.mul(tensor, tensor, out=z3)
print(f"z3: {z3}")


y1: tensor([[1.0531, 1.3263, 1.2301],
        [1.3263, 2.3386, 2.1956],
        [1.2301, 2.1956, 2.0824]], device='cuda:0') 
 y2: tensor([[1.0531, 1.3263, 1.2301],
        [1.3263, 2.3386, 2.1956],
        [1.2301, 2.1956, 2.0824]], device='cuda:0') 
 y3: tensor([[0.1789, 0.3940, 0.6028, 0.4457],
        [0.3137, 0.6821, 0.4585, 0.1410],
        [0.9903, 0.0969, 0.2118, 0.0743]], device='cuda:0')
y3: tensor([[1.0531, 1.3263, 1.2301],
        [1.3263, 2.3386, 2.1956],
        [1.2301, 2.1956, 2.0824]], device='cuda:0')
z1: tensor([[0.1704, 0.1596, 0.0550, 0.6681],
        [0.3906, 0.8475, 0.7250, 0.3755],
        [0.2396, 0.9350, 0.5885, 0.3193]], device='cuda:0') 
 z2: tensor([[0.1704, 0.1596, 0.0550, 0.6681],
        [0.3906, 0.8475, 0.7250, 0.3755],
        [0.2396, 0.9350, 0.5885, 0.3193]], device='cuda:0') 
 z3: tensor([[0.6392, 0.7499, 0.2362, 0.4064],
        [0.5451, 0.8273, 0.6144, 0.4762],
        [0.1730, 0.4504, 0.7805, 0.0768]], device='cuda:0')
z3: tensor([[0.1704, 0.1596,

/tmp/ipykernel_93108/160187974.py:6: UserWarning: An output with one or more elements was resized since it had shape [3, 4], which does not match the required output shape [3, 3]. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at /pytorch/aten/src/ATen/native/Resize.cpp:30.)
  torch.matmul(tensor, tensor.T,out=y3)


In [40]:
agg = tensor.sum()
print(agg)
print(agg.item(),type(agg),type(agg.item()))  # get the Python number from a tensor containing a single value

tensor(7.6627, device='cuda:0')
7.662703514099121 <class 'torch.Tensor'> <class 'float'>


In [42]:
print(tensor)
tensor.add_(5)
print(tensor)

tensor([[0.4128, 0.3994, 0.2346, 0.8174],
        [0.6250, 0.9206, 0.8515, 0.6128],
        [0.4895, 0.9669, 0.7671, 0.5651]], device='cuda:0')
tensor([[5.4128, 5.3994, 5.2346, 5.8174],
        [5.6250, 5.9206, 5.8515, 5.6128],
        [5.4895, 5.9669, 5.7671, 5.5651]], device='cuda:0')


In [ ]:
t = torch.ones(5)
print(f"t: {t}, type: {type(t)}")

n = t.numpy()
print(f"n: {n}, type: {type(n)}")


t: tensor([1., 1., 1., 1., 1.]), type: <class 'torch.Tensor'>
n: [1. 1. 1. 1. 1.], type: <class 'numpy.ndarray'>


In [ ]:
# 这是因为它们共享内存空间，对一个进行修改会影响另一个
t.add_(5)
print(f"t: {t}, type: {type(t)}")
print(f"n: {n}, type: {type(n)}")

t: tensor([6., 6., 6., 6., 6.]), type: <class 'torch.Tensor'>
n: [6. 6. 6. 6. 6.], type: <class 'numpy.ndarray'>


In [46]:
n += 5
print(f"t: {t}, type: {type(t)}")
print(f"n: {n}, type: {type(n)}")

t: tensor([11., 11., 11., 11., 11.]), type: <class 'torch.Tensor'>
n: [11. 11. 11. 11. 11.], type: <class 'numpy.ndarray'>


In [47]:
n = np.ones(5)
t = torch.from_numpy(n)

In [48]:
np.add(n,1,out=n)
print(f"t: {t}, type: {type(t)}")
print(f"n: {n}, type: {type(n)}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64), type: <class 'torch.Tensor'>
n: [2. 2. 2. 2. 2.], type: <class 'numpy.ndarray'>
